#!/bin/bash
# File: daemon
# This script manipulates daemons in /etc/rc.d on Arch Linux systems.

# Version 2.0  (8. January 2011)

# Copyright (c) 2010-2011, Ben Morgan <uv.sound@gmail.com>
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# get_daemon_commands() and get_all_daemon_commands()
# by Andrwe Lord Weber [http://andrwe.org]

dir_available='/etc/rc.d'
dir_running='/var/run/daemons'
quit_on_fail=false

function version () {
    echo "arch-daemon version 2.0 (8. January 2011)"
}

function help () {
    version
    echo 'Easily manipulate daemons in /etc/rc.d on Arch Linux.'
    echo 
    echo 'Usage: daemon [options] [command] <daemons>'
    echo '  --command cmd  -c   send the given command'
    echo '  --fail         -f   quit when a service does not exist'
    echo '                      or when a service quits with an error'
    echo '  --list         -l   list started daemons and quit'
    echo '  --available    -a   list all available daemons and quit'
    echo '  --arguments    -z   list sendable commands to given daemons and quit'
    echo '  --help         -h   display this help and quit'
    echo '  --version      -v   display the version and quit'
    echo 
    echo 'Any command may be given; if no command is given,'
    echo 'then `start` is assumed. Some commands have aliases:'
    echo '  s=start,  t=stop,  r=restart,  l=reload'
    echo 
    echo 'If the first argument does not exist in /etc/rc.d as'
    echo 'a daemon, then it is assumed to be a command.'
    echo 'If a aliased command exists as a daemon in /etc/rc.d,'
    echo 'then the command can be send with `-c command`.'
    echo 
}

# Print currently running daemons
function print_running () {
    echo "Currently running daemons:"
    /bin/ls -1 $dir_running | xargs -I daemon echo "  daemon"
}

# Print all available daemons
function print_available () {
    echo "All available daemons:"
    /bin/ls --color=never --hide=functions* $dir_available
}

# Print available commands for an array of daemons
function print_arguments () {
    array=$1  # array of daemons to print info for
    
    # check that the array of services is not empty
    if [ -z ${array[0]} ]; then
        exec 1>&2  # send output to stderr
        help
        exit 2
    fi

    echo "Available commands for the daemon(s):"
    for service in ${array[@]}; do
        # check if daemon is available
        if ! daemon_available $service; then
            echo "  daemon '$service' does not exist!" 1>&2
        else
            get_daemon_commands $service
            echo "  $service: ${last_daemon_commands[@]}"
        fi
    done
}

# Quit on fail
function fail () {
    if [ $quit_on_fail == true ]; then
        echo "failing." 1>&2
        exit 2
    fi
}

# Check if a daemon is available
function daemon_available () {
    test -f $dir_available/$1
    return $?
}

# TODO: figure out what to do with this function :P
declare -a all_daemon_commands
function get_all_daemon_commands () {
    # Uses globbing to go through all the daemons in /etc/rc.d
    get_daemon_commands "!(*.pac(orig|new|save)|functions*|*functions)"
    all_daemon_commands=$last_daemon_commands
}

# Stores the supported commands of the daemon in the array below
declare -a last_daemon_commands
function get_daemon_commands () {
    # Get all of the possible commands that there are, by going through each case.
    last_daemon_commands=$(sed '/#.*sh/,/^.*case\s*"*\${*1}*"*.*/ { /^.*case\s*"*\${*1}*"*.*/!d };s/^.*case\s*"*\${*1}*"*.*/;;/g;/;;/,/^\s*.*)\s*$/ !d;/^\s*.*)\s*$/ !d;/\*/d;/;;/d;s/\s*//g;s/)//g;s/|/ /g' $dir_available/$1 | LANG=C sort | uniq | tr '\n' ' ')
}

# Check if a daemon supports a command;
function daemon_has_command () {
    get_daemon_commands $1
    for i in ${last_daemon_commands[@]}; do
        if [ $i == $2 ]; then
            return 0
        fi
    done
    
    return 1
}

# Check a service if it fulfills the requirements
# i.e. it exists and supports the command
function check_service () {
    service=$1  # the service (e.g. cups)
    cmd=$2      # the command (e.g. start)

    # check if daemon is available
    if ! daemon_available $service; then
        echo "daemon '$service' does not exist!" 1>&2
        return 1
    fi
    
    # check if daemon supports given command
    if ! daemon_has_command $service $cmd; then
        echo "daemon '$service' does not support the command '$cmd'" 1>&2 
        echo "        $service supports: ${last_daemon_commands[@]}" 1>&2
        return 1
    fi

    return 0
}

# Run a service
function run () {
    service=$1  # the service (e.g. cups)
    cmd=$2      # the command (e.g. start, stop, restart, reload)
    
    # Run the service, if it exists (we'll trust the user on the command)
    if daemon_available $service; then
        /etc/rc.d/$service $cmd
    fi
    return $?
}

# Run all of the services
function runall () {
    array=$1  # the array of services
    cmd=$2    # the command to be executed

    # Check all the services first
    status=0
    for service in ${array[@]}; do
        check_service $service $cmd
        status=$(($status + $?))
    done
    [ $status -ne 0 ] && fail

    # Make sure that we are root
    if [ "$(id -u)" != "0" ]; then
        echo "root access required." 1>&2
	    exit 1
    fi
    
    # Run all the services
    for service in ${array[@]}; do
        run $service $cmd
        [ $? -ne 0 ] && fail
    done
}


# Make sure that we have some arguments
if [ $# -eq 0 ]; then
    exec 1>&2  # send output to stderr
    help
    exit 1
fi

# Parse the arguments and compile a command
# Default command is "start" if not specified
declare -a array
cmd="start"
count=-1
print_commands=false
while [ $# -ne 0 ]; do
    case $1 in
        -a|--available )
            print_available
            exit 0;;
        -l|--list )
            print_running
            exit 0;;
        -h|--help )
            help
            exit 0;;
        -v|--version )
            version
            exit 0;;
        -z|--arguments )
            print_commands=true
            shift 1;;
        -f|--fail )
            quit_on_fail=true
            shift 1;;
        -c|--command )
            cmd=$2
            if [ $count -eq -1 ]; then
                count=0
            fi
            shift 2;;
        * )
            if [ $count -eq -1 ]; then
                # We have the first non-option, see if it is a command
                count=0
                case $1 in
                    s|start  ) cmd="start";;
                    t|stop   ) cmd="stop";;
                    r|restart) cmd="restart";;
                    l|reload ) cmd="reload";;
                    * )
                        if daemon_available $1; then
                            array[$count]=$(basename $1)
                            count=$(($count + 1))
                        else
                            cmd=$1
                        fi
                esac
            else
                # basename the service to prevent running other applications
                # (so you can't run a service ../../home/someuser/bad-app.sh)
                array[$count]=$(basename $1);
                count=$(($count + 1))
            fi
            shift 1
    esac
done

if $print_commands; then
    print_arguments $array
else
    runall $array $cmd
fi
exit $?

