#!/bin/bash
# File: daemon
# This script manipulates daemons in /etc/rc.d on Arch Linux systems.

# Version 1.10  (2. January 2011)

# Copyright (c) 2011, Ben Morgan <uv.sound@gmail.com>
# 
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
# 
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

function version () {
    echo "arch-daemon version 1.10 (2. January 2011)"
}

function help () {
    echo "arch-daemon manipulates services (daemons)"
    echo "on Arch Linux: start, stop and restart"
    echo ""
    echo "Usage: daemon [-s|-t|-r|-ts] <daemons>"
    echo "If no flag is specified, -s is assumed"
    echo "  --list         -l   list started daemons"
    echo "  --available    -a   list all available daemons"
    echo "  --start        -s   send: start"
    echo "  --stop         -t   send: stop"
    echo "  --restart      -r   send: restart"
    echo "  --reload       -rl  send: reload (e.g. httpd)"
    echo "  --stop-start   -ts  send: stop and then start"
    echo "  --help         -h   display this help"
    echo "  --version      -v   display the version"
    echo "  --quit-on-fail -q   quit when a services does not exist"
    echo "                      or when a service quits with an error"
    echo ""
}

function list () {
    echo "Currently running daemons:"
    /bin/ls -1 /var/run/daemons | xargs -I daemon echo "  daemon"
}

function available () {
    echo "All available daemons:"
    /bin/ls --color=never --hide=functions* /etc/rc.d
    #ls -1 /etc/rc.d | xargs -I daemon echo "  daemon"
}

function run () {
    # basename the service to prevent running other applications
    # (so you can't run a service ../../home/someuser/bad-app.sh)
    service=$(basename $1)  # the service (e.g. cups)
    cmd=$2       # the command (start, stop, restart, reload)
    
    if [ ! -f /etc/rc.d/$service ]; then
        echo "daemon '$service' does not exist!"
        if [ "$quitonfail" == "1" ]; then
            exit 2
        fi
        return 2
    fi
    
    # Make sure that we are root
    if [ "$(id -u)" != "0" ]; then
	    echo "root access required."
	    exit 1
    fi

    /etc/rc.d/$service $cmd

    if [ "$quitonfail" == "1" ]; then
        if [ "$?" != "0" ]; then
            exit 2
        fi
    fi
}

function runall () {
    array=$1  # the array of services
    cmd=$2    # the command to be executed
    
    if [ "$cmd" == "stopstart" ]; then
        runall $array "stop";
        runall $array "start";
    else
        for service in ${array[@]}; do
            run $service $cmd
        done
    fi 
}



# Parse the arguments and compile a command
quitonfail=0;
if [ $# -gt 0 ]; then
    count=0;
    array=();
    cmd="start"; # default if no flag specified
    for arg in $@; do
        case $arg in
            -a|--available ) available; exit 0;;
            -l|--list      ) list; exit 0;;
            -h|--help      ) help; exit 0;;
            -v|--version   ) version; exit 0;;
            -s|--start     ) cmd="start";;
            -t|--stop      ) cmd="stop";;
            -r|--restart   ) cmd="restart";;
           -rl|--reload    ) cmd="reload";;
           -ts|--stop-start) cmd="stopstart";;
            -q|--quit-on-fail) quitonfail=1;;
             *             ) array[$count]=$arg; count=$count+1;;
        esac
    done
    runall $array $cmd
    exit $?
else
    help
    exit 1
fi

exit 128

